### ISSUE TITLE
Update dependencies to allow PHP 8

### ISSUE THREAD

**Issue by karptonite** [pubsubhubbub/php-subscriber#12]
Judging from [this fork](https://github.com/SeismicInc/php-subscriber), it appears that all that would be needed to allow this to be used for PHP 8 is to update the dependencies in composer. Is anyone still watching this repository who could do so?

**Comment by maksverver** [comment]
Thanks for the suggestion, Daniel. I've updated `composer.json` to allow PHP 8.

Caveat: I haven't tested if this code actually works on PHP 8. Please let me know if you run into issues, preferably with a patch attached.
